CREATE TABLE [dbo].[LogEntry]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[LogDate] DATETIME NOT NULL, 
	[LogType] NVARCHAR(20) NOT NULL,
	[FeatureName] NVARCHAR(1000) NOT NULL,
	[RequestIpAddress] NVARCHAR(20) NOT NULL,
	[RequestUrl] NVARCHAR(1000) NOT NULL,
	[ReferrerUrl] NVARCHAR(1000) NOT NULL, 
	[UserAgent] NVARCHAR(1000) NOT NULL,
	[Username] NVARCHAR(100) NOT NULL,
	[Message] NVARCHAR(MAX) NOT NULL
)
